# Generated by Django 5.2.3 on 2026-03-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ImageField(blank=True, default='default.png', upload_to='photos/products'),
        ),
    ]
