# Generated by Django 3.1.5 on 2021-04-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Images/None/noimg.jpg', upload_to='userprofile/'),
        ),
    ]
