# Generated by Django 3.1.5 on 2021-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210420_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile/img/noimg.jpg', upload_to='img/'),
        ),
    ]
