# Generated by Django 3.1.5 on 2021-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Cards', 'Cards'), ('Net Bankin', 'Net Banking')], default='Cash On Delivery', max_length=100),
        ),
    ]
