# Generated by Django 3.1.5 on 2021-04-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210416_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Images',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
