# Generated by Django 3.1.5 on 2021-04-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
