# Generated by Django 3.1.5 on 2021-04-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20210416_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Cards', 'Cards'), ('Net Bankin', 'Net Banking')], default='Cash On Delivery', max_length=100)),
                ('amount_paid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField()),
                ('Images', models.ImageField(blank=True, upload_to='photos/products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentPaypal',
        ),
    ]
